config/routes.rb
AaltoApps::Application.routes.draw do
  # prefix all urls with language (e.g. /en/rest_of_url)
  filter :locale

  get 'session' => 'sessions#index' # login page
  post 'session' => 'sessions#create'
  get 'session/cas' => 'sessions#create', :cas => true, :as => :cas_session
  delete 'session' => 'sessions#destroy'

  resources :users do
    resources :products
    resources :comments
    resources :ratings
  end
  
  resources :platforms do
    resources :products
  end
  
  resources :products do
    resources :platforms
    resources :comments
    resources :downloads
    resources :ratings

    member do
      put :block
      put :approve
      put :request_approval
      put :promote
      put :demote
    end

    collection do
      namespace 'platform' do
        get ':platform' => 'products#index'
      end

      get 'tag/:tags' => 'products#index', :as => :tag

      get :autocomplete_tags
    end
  end

  resources :comments, :belongs_to => :products

  resources :pages, :only => :show

  # Receives proxy-granting ticket from CAS server.
  # This must be called using HTTPS or from localhost for security reasons.
  get 'receive_pgt' => 'cas_proxy_callback#receive_pgt'
  # used internally for retrieving PGTs
  get 'retrieve_pgt' => 'cas_proxy_callback#retrieve_pgt'

  root :to => "products#mainpage"

  # if no other routes match, render error page
  match '*path' => ApplicationController.action(:render_404)
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  load_and_authorize_resource :except => :add_product

  # GET /platforms
  # GET /platforms
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @platforms }
    end
  end

  # GET /platforms/new
  # GET /platforms/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @platform }
    end
  end

  # GET /platforms/1
  # GET /platforms/1
  def show
    respond_to do |format|
      format.html # edit.html.erb
      format.xml  { render :xml => @platform }
    end
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms
  # POST /platforms.xml
  def create
    if @platform.save
      respond_to do |format|
        format.html { redirect_to({:action => "show", :id => @platform.id}, :notice => _("Platform was successfully created"))}
        format.xml { render :xml => @platform, :status => :created, :location => @loatform}
      end
    else
      respond_to do |format|
        format.html { render :action => "new" }
        format.xml { render :xml => @platform.errors, :status => :unprocessable_entity}
      end
    end
  end

  # PUT /platforms/1
  # PUT /platforms/1.xml
  def update
    respond_to do |format|
      if @platform.update_attributes(params[:platform])
        format.html { redirect_to({:action => "show", :id => @platform.id}, :notice => _('Platform was successfully updated.')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @platform.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.xml
  def destroy
    respond_to do |format|
      begin
        @platform.destroy
      rescue ActiveRecord::ActiveRecordError => e
        errmsg = if e.is_a? ActiveRecord::DeleteRestrictionError
          _('Cannot delete platform that has products')
        else
          e.to_s
        end

        format.html { redirect_to({:action => "index"}, :alert => errmsg) }
        format.xml  { render :xml => {:error => errmsg}.to_xml(:root => :errors), :status => :conflict }
      else
        format.html { redirect_to({:action => "index"}, :notice => _("Platform was successufully deleted.")) }
        format.xml  { head :ok }
      end
    end
  end

  def add_product
    product = Product.find(params[:id])
    platform = Platform.find(params[:product][:platform_ids])
    product.platforms << platform

    authorize! :add_platform, product

    product.save!
    redirect_to :back
  end
end

app/views/platforms/_form.html.erb
<%= form_for @platform do |f| %>
	<% if flash[:error] %>
    <div id="error_explanation">
      <h2><%= _("Validation errors prohibited this platform from being saved") %>:</h2>

      <ul>
      <% flash[:error].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, _("Name") %><br />
    <%= f.text_field :name, :class => 'textfield'  %>
  </div>

  <div class="field">
    <%= f.label :image_url, _("Category image url") %><br />
    <%= f.text_field :image_url, :class => 'textfield' %>
  </div>

  <div class="actions">
    <%= f.submit _("Submit"), :class => 'smallbutton' %>
  </div>
<% end %>

app/views/platforms/_login_menu.html.erb
<% if !logged_in? %>
<%= link_to _("login"), :controller => "sessions" %> :: 
<%= link_to _("register"), :controller => "users", :action => "new" %>
<% else %>
logged in as <%= current_user.username %>, <%= link_to _("logout"), "/sessions/", :method => :delete %>
<% end %>

app/views/platforms/edit.html.erb
<h1><%= _("Editing platform") %></h1>

<%= render 'form' %>

<%= button_to _('Back'), :back, :method => :get, :class => 'smallbutton' %>

app/views/platforms/index.html.erb
<div class="platform_list">
<h1><%= _("Listing platforms") %></h1>

<table>
  <tr>
    <th><%= _("Name") %></th>
    <th><%= _("Image url") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @platforms.each do |platform| %>
  <tr>
    <td><%= platform.name %></td>
    <td><%= link_to platform.image_url, platform.image_url %></td>
    <td><%= button_to _('Show'), platform_path(platform.id), :method => :get, :class => 'smallbutton' if can? :show, platform%></td>
    <td><%= button_to _('Edit'), edit_platform_path(platform.id), :method => :get, :class => 'smallbutton' if can? :edit, platform %></td>
    <td><%= button_to _('Destroy'), platform, :method => :delete,
                                    :confirm => _('Are you sure?'), :class => 'smallbutton' if can? :delete, platform %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to _('New Platform'), new_platform_path, :class => 'smallbutton', :method => :get if can? :new, Platform %>
</div>

app/views/platforms/new.html.erb
<h1><%= _("Add new platform") %></h1>

<%= render 'form' %>

<%= button_to _('Back'), :back, :method => :get, :class => 'smallbutton' %>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= _("Name") %>:</b>
  <%= @platform.name %>
</p>

<p>
  <b><%= _("Image URL") %>:</b>
  <%= @platform.image_url %>
</p>

<p>
  <b><%= _("Products") %>:</b>
  <% @platform.products.each do |product| %>
    <%= product.name %>
  <% end %>
</p>


<% if can? :edit, @platform %>
  <%= button_to _('Edit'), edit_platform_path(@platform.id), :method => :get, :class => 'smallbutton' %>
	<%= button_to _('List platforms'), platforms_path, :method => :get, :class => 'smallbutton' %>
<% end %>