config/routes.rb
AaltoApps::Application.routes.draw do
  # prefix all urls with language (e.g. /en/rest_of_url)
  filter :locale

  get 'session' => 'sessions#index' # login page
  post 'session' => 'sessions#create'
  get 'session/cas' => 'sessions#create', :cas => true, :as => :cas_session
  delete 'session' => 'sessions#destroy'

  resources :users do
    resources :products
    resources :comments
    resources :ratings
  end
  
  resources :platforms do
    resources :products
  end
  
  resources :products do
    resources :platforms
    resources :comments
    resources :downloads
    resources :ratings

    member do
      put :block
      put :approve
      put :request_approval
      put :promote
      put :demote
    end

    collection do
      namespace 'platform' do
        get ':platform' => 'products#index'
      end

      get 'tag/:tags' => 'products#index', :as => :tag

      get :autocomplete_tags
    end
  end

  resources :comments, :belongs_to => :products

  resources :pages, :only => :show

  # Receives proxy-granting ticket from CAS server.
  # This must be called using HTTPS or from localhost for security reasons.
  get 'receive_pgt' => 'cas_proxy_callback#receive_pgt'
  # used internally for retrieving PGTs
  get 'retrieve_pgt' => 'cas_proxy_callback#retrieve_pgt'

  root :to => "products#mainpage"

  # if no other routes match, render error page
  match '*path' => ApplicationController.action(:render_404)
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ratings, :dependent => :destroy
  has_many :published, :class_name => "Product", :foreign_key => "publisher_id"
  has_many :comments
  attr_protected :is_admin, :receive_admin_email, :asi_id,
                 :terms, :no_asi_fetch, :cas_user
  validates :username, :password, :presence => { :on => :create, :unless => :cas_user }
  validates :terms, :acceptance => { :on => :create }
  validates :password, :confirmation => { :if => Proc.new { |user| user.password.present? } }
  validates :email, :presence => true
  attr_accessor :terms, :no_asi_fetch, :cas_user
  before_save :update_data_before_save
  
  PERSON_HASH_CACHE_EXPIRE_TIME = 0#15  #ALSO THIS CACHE TEMPORARILY OFF TO TEST PERFORMANCE WIHTOUT IT
  PERSON_NAME_CACHE_EXPIRE_TIME = 3.hours  ## THE CACHE IS TEMPORARILY OFF BECAUSE CAUSED PROBLEMS ON ALPHA: SEE ALSO COMMENTING OUT AT THE PLACE WHER CACHE IS USED!

  # supported ASI attributes:

  # read-only
  ASI_RO_ATTRIBUTES = [:username]

  # read/write
  ASI_RW_ATTRIBUTES = [:name, :address, :phone_number, :email,
                       :description, :gender, :birthdate,
                       :website, :phone_number, :irc_nick, :msn_nick]

  # write-only
  ASI_WO_ATTRIBUTES = [:password, :consent]

  # nested read/write attributes
  # these are accessed using the innermost name
  ASI_RW_NESTED_ATTRIBUTES = {
    :name => [:family_name, :given_name],
    :address => [:postal_code, :street_address, :locality],
  }

  # attributes that cannot be unset
  ASI_NONUNSETTABLE_ATTRIBUTES = Set.new [:password, :gender]

  def assign_attributes(new_attributes, *args)
    new_attributes = new_attributes.with_indifferent_access  # allow both string and symbol keys

    # extract nested ASI attributes given as nested hash entries
    nested = new_attributes.slice(*ASI_RW_NESTED_ATTRIBUTES.keys)
      .select { |attr, value| value.is_a? Hash }
    nested.each do |attr, subattrs|
      if subattrs.is_a? Hash
        new_attributes.delete attr
        new_attributes.merge! subattrs
      end
    end

    # allow setting read-only fields for new records
    new_attributes.extract!(*ASI_RO_ATTRIBUTES).each do |attr, value|
      if new_record?
        asi_attributes[attr.to_s] = value
      else
        raise ActiveRecord::AttributeAssignmentError, "Attribute #{attr} is read-only"
      end
    end

    # this will call the setter methods for normal and ASI attributes
    super(new_attributes, *args)
  end

  # make getters for readable ASI attributes
  (ASI_RO_ATTRIBUTES + ASI_RW_ATTRIBUTES).each do |attr|
    define_method attr do
      if asi_attributes.has_key? attr.to_s
        asi_attributes[attr.to_s]
      elsif asi_id && !no_asi_fetch
        p = get_person_hash
        p && p[attr.to_s]
      end
    end
  end

  # make getters for locally set values of write-only attributes
  ASI_WO_ATTRIBUTES.each do |attr|
    define_method attr do
      asi_attributes[attr.to_s]
    end
  end

  # make setters for writable ASI attributes
  (ASI_WO_ATTRIBUTES + ASI_RW_ATTRIBUTES).each do |attr|
    define_method "#{attr}=" do |val|
      val = nil if val == ''
      # Set value. If nil and the attribute is non-unsettable, don't change the value.
      asi_attributes[attr.to_s] = val unless val.nil? && ASI_NONUNSETTABLE_ATTRIBUTES.member?(attr)
    end
  end

  # make getters and setters for nested attributes
  ASI_RW_NESTED_ATTRIBUTES.each do |attr, subattrs|
    subattrs = [subattrs] unless subattrs.is_a? Enumerable
    attr_s = attr.to_s
    subattrs.each do |subattr|
      define_method subattr do
        a = self.send(attr)
        a && a[subattr.to_s]
      end

      define_method "#{subattr}=" do |val|
        val = nil if val == ''
        asi_attributes[attr_s] ||= Hash.new
        asi_attributes[attr_s][subattr.to_s] = val
      end
    end
  end

  # readers for special nested unstructured fields:

  def unstructured_name
    n = name
    n && n['unstructured']
  end

  def unstructured_address
    a = name
    a && a['unstructured']
  end

  # special reader for ASI's updated_at to prevent name collision with local updated_at
  def asi_updated_at
    asi_attributes['updated_at'] ||
      if asi_id && !no_asi_fetch
        get_person_hash['updated_at']
      else
        nil
      end
  end

  # return ASI attributes as hash
  def asi_data(include_email = false)
    hash = asi_attributes
    hash.reverse_merge!(get_person_hash)  if asi_id && !no_asi_fetch
    hash.delete('email')  unless include_email
    hash
  end

  attr_writer :asi_cookie
  def asi_cookie
    @asi_cookie || Session.aaltoapps_cookie
  end

  # Search users from ASI with given parameters. Returns User records.
  # If prevent_asi_fetch is true, the User records have no_asi_fetch set,
  # which means that the record will not try to fetch missing data from ASI
  # server.
  def self.asi_find(params={}, prevent_asi_fetch=true)
    response = UserConnection.find_people(params, Session.aaltoapps_cookie)
    if response && response['entry'].present?
      response['entry'].map do |entry|
        entry[:asi_id] = entry.delete 'id'
        entry[:no_asi_fetch] = prevent_asi_fetch
        User.new(entry)
      end
    else
      []
    end
  end

  def is_admin?
    is_admin
  end

  # clear changed ASI attributes on reload
  def reload
    @asi_attributes.clear
    super
  end

  def to_xml(options = {}, &block)
    options[:only] = Array.wrap(options[:only])
    options[:except] = Array.wrap(options[:except])
    options[:methods] = Array.wrap(options[:methods])

    if  (options[:only].empty? || options[:only].member?('asi_data') || options[:only].member?(:asi_data)) &&
        ! (options[:except].member?('asi_data') || options[:except].member?(:asi_data))
      options[:methods] |= [ :asi_data ]
    end
    if options[:only].empty?
      options[:only] = attributes.keys - options[:except].map(&:to_s)
    else
      options[:only] &= attributes.keys + attributes.keys.map(&:to_sym)
    end

    super(options, &block)
  end


  private

  def update_data_before_save
    if asi_id
      # update user information in ASI
      if @asi_attributes.present?
        params = @asi_attributes.dup

        if params["name"] || params[:name]
          # If name is going to be changed, expire name cache
          Rails.cache.delete("person_name/#{self.id}")
          Rails.cache.delete("given_name/#{self.id}")
        end
        UserConnection.put_attributes(params, asi_id, asi_cookie)
      end

    else

      # If no asi_id, try to create a new person to ASI
      person_hash = {
        :person => asi_attributes.slice(*%w(username password email)).
                                  merge!(:consent => APP_CONFIG.consent_versions[I18n.locale])
      }
      response = UserConnection.create_person(person_hash, asi_cookie)

      # Because ASI now associates the used cookie to a session for the newly created user
      # Change the cookie to nil if it was used (because now it is no more an app-only cookie)
      Session.update_aaltoapps_cookie  if asi_cookie == Session.aaltoapps_cookie

      # Pick id from the response
      self.asi_id = response["entry"]["id"]
    end

    # if language not set, set it to fallback value
    self.language ||= APP_CONFIG.fallback_locale
  end

  def self.cache_fetch(id,cookie)
    # FIXME: CACHING DISABLED DUE PROBLEMS AT ALPHA SERVER
    UserConnection.get_person(id, cookie)  # A line to skip the cache temporarily
    #Rails.cache.fetch(cache_key(id,cookie), :expires_in => PERSON_HASH_CACHE_EXPIRE_TIME) {PersonConnection.get_person(id, cookie)}
  end


  def asi_attributes
    @asi_attributes ||= Hash.new
  end

  def get_person_hash
    begin
      person_hash = User.cache_fetch(asi_id, asi_cookie)
    rescue RestClient::ResourceNotFound => e
      #Could not find person with that id in ASI Database!
      return nil
    end

    return person_hash["entry"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource :except => [:index, :create, :terms]

  # GET /users
  # GET /users.xml
  def index
    if params[:all].present?
      authorize! :asi_index, User
      @users = User.asi_find(params.except(:all))
    else
      authorize! :index, User
      @users = User.accessible_by(current_ability)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.xml
  def create
    authorize! :create, User
    @new_session = Session.create
    session[:cookie] = @new_session.cookie
    @user = User.new(params[:user])
    @user.asi_cookie = @new_session.cookie
    begin
      @user.save!
    rescue ActiveRecord::RecordInvalid
      render :action => "new" and return
    rescue RestClient::RequestFailed => e
      flash.now[:error] = JSON.parse(e.response.body)["messages"]
      render :action => "new" and return
    end

    session[:current_user_id] = @user.id

    respond_to do |format|
      format.html { redirect_to(@user, :notice => _("Logged in")) }
      format.xml  { render :xml => @user, :status => :created, :location => @user }
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    # if admin status changes, check authorization for the change
    if params[:user].has_key?(:is_admin)
      was_admin = @user.is_admin?
      @user.is_admin = params[:user].delete :is_admin
      authorize! :grant_admin_role, @user if !was_admin && @user.is_admin?
      authorize! :revoke_admin_role, @user if was_admin && !@user.is_admin?
    end

    if params[:user].has_key?(:receive_admin_email)
      prev_val = @user.receive_admin_email
      @user.receive_admin_email = params[:user].delete :receive_admin_email
      authorize! :set_receive_admin_email, @user if !prev_val && @user.receive_admin_email
      authorize! :unset_receive_admin_email, @user if prev_val && !@user.receive_admin_email
    end

    @user.asi_cookie = session[:cookie]
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(:back, :notice => _('User was successfully updated.')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_link(user, type=:link)
    username = user.username
    if username
      case type
      when :nolink
        content_tag :span, username, :class => 'user-link user-link-noerror user-link-nolink'
      else
        link_to username, user, :class => 'user-link user-link-noerror user-link-normal'
      end
    else
      # unknown user (e.g. user deleted)
      content_tag :span, s_('user_link|unknown'), :class => 'user-link user-link-undefined user-link-unknown'
    end
  rescue SystemCallError, RestClient::Exception
    # error in ASI connection
    content_tag :span, s_('user_link|error!'), :class => 'user-link user-link-undefined user-link-error'
  end
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:id => 'user_form'} do |f| %>
  <% if flash[:error] || @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= _("Validation errors prohibited user information from being saved") %>:</h2>

      <ul>
      <%
        # combine error messages from the following sources:
        # - custom error message in the first position if terms not accepted
        # - flash error messages
        # - form error messages except the message for not accepting terms
        errors = []
        if @user.errors[:terms].present?
          errors << _('In order to register, you must accept the OtaSizzle "Terms and Conditions".')
          @user.errors[:terms] = []
        end
        errors += flash[:error] || []
        errors += @user.errors.full_messages
        errors.each do |msg|
      %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %> *<br />
      <%= f.text_field :username, :class=>'textfield' %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><% if @user.new_record? %> *<% end %><br />
    <%= f.password_field :password, :class=>'pwfield' %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><% if @user.new_record? %> *<% end %><br />
    <%= f.password_field :password_confirmation, :class=>'pwfield' %>
  </div>

  <div class="field">
    <%= f.label :language %> *<br />
    <%= f.select :language, @available_locales.map { |l| [l[:name], l[:id]] },
                            { :selected => @user.language || I18n.locale.to_s },
                            { :class => 'otherfield' } %>
  </div>

  <div class="field">
    <%= f.label :email %> *<br />
    <%= f.text_field :email, :class=>'textfield' %>
  </div>

  <% unless @user.new_record? %>
    <div class="field">
      <%= f.label :birthdate %><br />
      <%= f.text_field :birthdate, :class => 'textfield' %>
    </div>

    <div class="field">
      <%= f.label :gender %><br />
      <%= f.select :gender, [[_('Unspecified'), ''], [_('Male'), 'MALE'], [_('Female'), 'FEMALE']]%>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description, :class => 'textfield' %>
    </div>

    <div class="field">
      <%= f.label :website %><br />
      <%= f.text_field :website, :class => 'textfield' %>
    </div>

    <div class="field">
      <%= f.label :phone_number %><br />
      <%= f.text_field :phone_number, :class => 'textfield' %>
    </div>

    <div class="field">
      <%= f.label :given_name %><br />
      <%= f.text_field :given_name, :class => 'textfield'%>
    </div>

    <div class="field">
      <%= f.label :family_name %><br />
      <%= f.text_field :family_name, :class => 'textfield' %>
    </div>

    <div class="field">
      <%= f.label :street_address %><br />
      <%= f.text_field :street_address, :class => 'textfield' %>
    </div>

    <div class="field">
      <%= f.label :postal_code %><br />
      <%= f.text_field :postal_code, :class => 'textfield' %>
    </div>

    <div class="field">
      <%= f.label :locality %><br />
      <%= f.text_field :locality, :class => 'textfield' %>
    </div>

    <% if (@user.receive_admin_email && can?(:unset_receive_admin_email, @user)) ||
          (!@user.receive_admin_email && can?(:set_receive_admin_email, @user)) %>
      <div class="field">
        <%= f.label :receive_admin_email, _('Receive admin e-mail') %><br />
        <%= f.check_box :receive_admin_email, :class => 'checkbox-label' %>
      </div>
    <% end %>

  <% else %>

    <div class="field">
      <%= f.check_box :terms %>
      <%=
        f.label :terms,
                substitute_links(
                  _('I accept the OtaSizzle [[Terms and Conditions]]'),
                  page_path(:user_terms),
                  :target => '_blank', :class => 'ajax-popup' ),
                :class => 'checkbox-label'
      %>
    </div>

  <% end %>

  <div class="actions">
    <%= f.submit( @user.new_record? ? _('Register') : _('Save'), :class => 'smallbutton') %>
  </div>
<% end %>

app/views/users/_grant_admin_role.html.erb
<%= form_for grant_admin_role do |f| %>
  <%= f.hidden_field :is_admin, :value => true %>
  <%= f.submit _('Grant administrator role'), :class => 'smallbutton' %>
<% end %>

app/views/users/_login_menu.html.erb
<div id="login-menu">
  <% if !logged_in? %>
    <%= button_to _("Login"), { :controller => "sessions" }, :class => 'smallbutton', :method => :get %>
    <%= button_to _("Register"), { :controller => "users", :action => "new" }, :class => 'smallbutton', :method => :get %>
  <% else %>
    <%= raw _("Logged in as %{username}") % {:username => user_link(current_user)} %>
    <%= button_to _("Logout"), { :controller => "sessions", :action => "destroy" }, :method => :delete, :class=> 'smallbutton' %>
  <% end %>
</div>

app/views/users/_revoke_admin_role.html.erb
<%
  user = revoke_admin_role
  attrs = if user == current_user
    { :onsubmit => 'return confirm("' + _('Are you sure you want to revoke your own administrator role?') + '");' }
  else
    {}
  end
%>
<%= form_for user, :html => attrs do |f| %>
  <%= f.hidden_field :is_admin, :value => false %>
  <%= f.submit _('Revoke administrator role'), :class => 'smallbutton' %>
<% end %>

app/views/users/edit.html.erb
<h1><%= _("Editing user") %></h1>

<%= render 'form' %>

<%= button_to _('Show'), @user, :class => 'smallbutton', :method => :get  %>
<%= button_to _('Back'), :back, :class => 'smallbutton', :method => :get  %>

app/views/users/index.html.erb
<div align="left">
<h1><%= _("Listing users") %></h1>

<table>
  <tr>
    <th><%= _("Username") %></th>
    <th><%= _("Firstname") %></th>
    <th><%= _("Lastname") %></th>
    <th><%= _("Type") %></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.given_name %></td>
    <td><%= user.family_name %></td>
    <td><%= case
            when user.is_admin? then  _('administrator')
            when user.persisted? then _('normal user')
            else                      _('non-local user')
            end
        %></td>
    <% if user.persisted? %>
      <td><%= button_to _('Show'), user_path(user), :method => :get, :class => 'smallbutton' if can? :show, user %></td>
      <td><%= button_to _('Edit'), edit_user_path(user), :method => :get, :class => 'smallbutton' if can? :edit, user %></td>
      <td><%= button_to _('Destroy'), user, :confirm => _('Are you sure?'), :method => :delete, :class => 'smallbutton' if can? :delete, user %></td>
      <td>
        <% if user.is_admin? && can?(:revoke_admin_role, user) %>
          <%= render :partial => '/users/revoke_admin_role', :object => user %>
        <% elsif !user.is_admin? && can?(:grant_admin_role, user) %>
          <%= render :partial => '/users/grant_admin_role', :object => user %>
        <% end %>
      </td>
    <% else %>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= button_to _('New User'), new_user_path, :class => 'smallbutton', :method => :get %>
</div>

app/views/users/new.html.erb
<h1><%= _("Register to aaltoapps") %></h1>

<%= render 'form' %>

<%= button_to _('Back'), :back, :class => 'smallbutton', :method => :get %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= _("Username") %>:</b>
  <%= @user.username %>
</p>

<p>
  <b><%= _("Firstname") %>:</b>
  <%= @user.given_name %>
</p>

<p>
  <b><%= _("Lastname") %>:</b>
  <%= @user.family_name %>
</p>

<p>
  <b><%= _("Type") %>:</b>
  <% if @user.is_admin? %>
    <%= _('administrator') %>
    <%= render :partial => '/users/revoke_admin_role', :object => @user if can?(:revoke_admin_role, @user) %>
  <% else %>
    <%= _('normal user') %>
    <%= render :partial => '/users/grant_admin_role', :object => @user if can?(:grant_admin_role, @user) %>
  <% end %>
</p>

<% if can? :view_email_address, @user %>
  <p>
    <b><%= _("Email") %>:</b>
    <%= @user.email %>
    <% if @user.receive_admin_email %>
      (<%= _("receives admin email") %>)
    <% end %>
  </p>
<% end %>

<p>
  <b><%= _("Published Products") %>:</b>
  <%= map_join_nowrap(@user.published) { |p| link_to p.name, p } %>
</p>


<% if can? :edit, @user %>
  <%= button_to _('Edit'), edit_user_path(@user), :class => 'smallbutton', :method => :get %>
<% end %>
<%= button_to _('Back'), :back, :class => 'smallbutton', :method => :get %>