config/routes.rb
AaltoApps::Application.routes.draw do
  # prefix all urls with language (e.g. /en/rest_of_url)
  filter :locale

  get 'session' => 'sessions#index' # login page
  post 'session' => 'sessions#create'
  get 'session/cas' => 'sessions#create', :cas => true, :as => :cas_session
  delete 'session' => 'sessions#destroy'

  resources :users do
    resources :products
    resources :comments
    resources :ratings
  end
  
  resources :platforms do
    resources :products
  end
  
  resources :products do
    resources :platforms
    resources :comments
    resources :downloads
    resources :ratings

    member do
      put :block
      put :approve
      put :request_approval
      put :promote
      put :demote
    end

    collection do
      namespace 'platform' do
        get ':platform' => 'products#index'
      end

      get 'tag/:tags' => 'products#index', :as => :tag

      get :autocomplete_tags
    end
  end

  resources :comments, :belongs_to => :products

  resources :pages, :only => :show

  # Receives proxy-granting ticket from CAS server.
  # This must be called using HTTPS or from localhost for security reasons.
  get 'receive_pgt' => 'cas_proxy_callback#receive_pgt'
  # used internally for retrieving PGTs
  get 'retrieve_pgt' => 'cas_proxy_callback#retrieve_pgt'

  root :to => "products#mainpage"

  # if no other routes match, render error page
  match '*path' => ApplicationController.action(:render_404)
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :publisher, :class_name => "User", :foreign_key => "publisher_id"
  belongs_to :category
  has_and_belongs_to_many :platforms, :uniq => true
  has_many :ratings, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :downloads, :dependent => :destroy
  has_attached_file :photo, :styles => { :mobile_thumb => "40x40#", :thumb => "75x75#", :small => "150x150>" },
    :url  => "/:class/:attachment/:id/:style_:basename.:extension",
    :default_url => "/images/:style_missing.png",
    :path => ":rails_root/public/:class/:attachment/:id/:style_:basename.:extension"
  acts_as_taggable_on :tags

  validates :name, :description, :url, :platforms, :presence => true
  validates :name, :length => { :minimum => 3 }
  validates :url, :length => { :minimum => 12 } # http://ab.cd
  validates :approval_state, :inclusion => { :in => %w( pending published blocked ) }
  validates :terms, :acceptance => true

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  #	validates_attachment_presence :photo

  attr_accessor :terms
  attr_accessor :delete_photo
  before_update :delete_photo_handler

  accepts_nested_attributes_for :downloads, :allow_destroy => true,
    # if no file given in new download field, ignore the download:
    :reject_if => proc { |attrs| !attrs['id'] && !attrs['file'] }
  before_save :recalculate_download_weights

  include MarkdownHelper
  markdown_fields :description

  attr_protected :publisher_id, :approval_state, :approval_date, :featured, :popularity

  after_initialize do |product|
    # set default value for approval_state according to configuration
    self.approval_state ||=
      if APP_CONFIG.require_approval_for_new_products == false  # must be false, not nil
        'published'
      else  # true, nil (not set) or anything except false
        'pending'
      end
  end

  def is_approved?
    self.approval_state == 'published'
  end

  def change_approval state
    self.approval_state = state.to_s
    self.approval_date = DateTime.now
    self.save!	
  end

private

  def delete_photo_handler
    self.photo = nil if self.delete_photo == '1'
  end

  def recalculate_download_weights
    i = 1
    downloads.sort_by(&:weight_as_float).each do |d|
      d.weight = i
      i += 1
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource(
    :only => [:index, :show, :new, :edit, :create, :update, :destroy,
              :block, :approve, :request_approval,
              :promote, :demote ] )
  before_filter :add_popularity, :only=>:show

  PRODUCTS_PER_PAGE = 6
  DEFAULT_SORT = "products.created_at DESC"
  DEFAULT_SORT_KEY = "created_at"
  ALLOWED_SORT_KEYS = %w(name created_at updated_at publisher avg_rating featured popularity)
  TAG_AUTOCOMPLETE_LIMIT = 20

private

  def fetch_data_for_index(params)
    page = params[:page] ? params[:page].to_i : 1

    if params[:platform_id]
      @platform = Platform.find(params[:platform_id])
      @products = @products.joins(:platforms).where(:platforms => {:id => @platform.id})
    end

    if params[:tags]
      @tags = ActsAsTaggableOn::TagList.from(params[:tags])
      @products = @products.tagged_with(params[:tags], :any => true)
    end

    if params[:myapps]
      @products = @products.where(:publisher_id => current_user.id)
      @view_type = :myapps
    elsif params[:approval]
      # this authorization might not be necessary; the results would be empty for normal users
      authorize! :approve, Product
      @approval_state = params[:approval]
      @products = @products.where(:approval_state => @approval_state)
      @view_type = :approval
    else
      @products = @products.where(:approval_state => 'published')
      @view_type = :index
    end

    if params[:q]
      # This SQL expression is database-specific. It works at least with
      # PostgreSQL. With SQLite it almost works: non-ascii characters are
      # compared case-sensitively.
      @products = @products.where(
        "lower(name) LIKE lower(:input) OR lower(description) LIKE lower(:input)",
        {:input => "%#{params[:q]}%"} )
      @search = params[:q]
    end

    @sort = params[:sort] || DEFAULT_SORT_KEY
    @products = @products.order(order_parameter(@sort))

    @products = @products.paginate(:page => page,
                                   :per_page => PRODUCTS_PER_PAGE)
  end

public

  def mainpage
    authorize! :index, Product
    @products = Product.accessible_by(current_ability)

    @featured_products = @products.where(:featured => true)

    # no need to load the product list for mobile site, because it won't
    # be shown on the mobile main page
    fetch_data_for_index(params) unless mobile_device?
  end

  # GET /products
  # GET /products.xml
  def index
    fetch_data_for_index(params)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    # Create a new Rating for the product copying the value of the
    # current user's current rating, if any.
    if logged_in?
      @new_rating_for_current_user = @product.ratings.build(
        :rating => @product.ratings.find_by_user_id(current_user.id) || nil
      )
    end

    comments = @product.comments.accessible_by(current_ability)
    @comments = comments.where(:admin_comment => false)
    @admin_comments = comments.where(:admin_comment => true)

    @new_admin_comment = @product.comments.build(:commenter => current_user)
    @new_admin_comment.admin_comment = true
    @new_admin_comment = nil unless can? :new, @new_admin_comment

    # which product approval state related buttons are applicable
    # in the current state:
    @approval_buttons =
      case @product.approval_state
        when 'pending'   then Set[:approve, :block]
        when 'published' then Set[:block]
        when 'blocked'   then Set[:request_approval, :approve]
      end
    @approval_buttons.keep_if { |action| can? action, @product }

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.xml
  def create
    @product.publisher_id = current_user.id
    if params[:cancel]
      @product = Product.new
      render :action => 'new'
    else
      respond_to do |format|
        if @product.save
          UserMailer.new_product(@product).deliver rescue nil

          format.html { redirect_to(@product, :notice => _('Product was successfully created.')) }
          format.xml  { render :xml => @product, :status => :created, :location => @product }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    # prevent deletion of new photo if delete photo checked when new photo uploaded
    params[:product].delete(:delete_photo) if params[:product][:photo].present?

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => _('Product was successfully updated.')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end

  def approve
    @product.change_approval 'published'
    UserMailer.product_approved(@product, current_user).deliver rescue nil
    redirect_to :back
  end

  def block
    @product.change_approval 'blocked'
    UserMailer.product_blocked(@product, current_user).deliver rescue nil
    redirect_to :back
  end

  def request_approval
    @product.change_approval 'pending'
    UserMailer.product_approval_request(@product).deliver rescue nil
    redirect_to :back
  end

  def promote
    @product.featured = true
    @product.save!
    redirect_to :back
  end

  def demote
    @product.featured = false
    @product.save!
    redirect_to :back
  end

  def autocomplete_tags
    pattern = params[:term]
    if pattern
      pattern.gsub!(/[%_]/, '\\\\\1')
      render :json =>
        Product.tag_counts.
          where('lower(tags.name) LIKE lower(?)', "#{pattern}%").
          order('lower(tags.name) ASC').
          limit(TAG_AUTOCOMPLETE_LIMIT).
          map(&:name)
    else
      render :json => []
    end
  end

private

  def add_popularity
    # increase popularity without triggering validations or callbacks
    Product.where(:id => params[:id]).update_all('popularity = popularity + 1')
  end

  def order_parameter(get_param)
    return DEFAULT_SORT if !get_param

    case get_param
    when 'popularity'
      sort = 'popularity DESC'
    when 'created_at'
      sort = 'created_at DESC'
    when 'avg_rating'
      sort = 'avg_rating IS NULL ASC, avg_rating DESC'
    when 'featured'
      sort = 'featured DESC'
    else
      sort = DEFAULT_SORT
    end

    return sort
  end

  def require_admin
    return if current_user && current_user.is_admin?
    redirect_to root_path
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  # returns localized approval status for given Product or status string
  def approval_status(param)
    param = param.approval_state if param.is_a?(Product)
    case param
      when 'pending'   then _('waiting for approval')
      when 'published' then _('published')
      when 'blocked'   then _('blocked')
    end
  end

  # Returns product list path with current request parameters (except page)
  # combined with parameters given in _params
  def products_path_with_params(_params)
    url_for( params.except(:page).
             merge(:controller => 'products', :action => 'index').
             merge(_params) )
  end

  # returns image tag for a Product's photo
  def product_photo(product, style = product.photo.default_style, img_options = {})
    # add width and height attributes if the style has constant image dimensions
    img_options.reverse_merge! case style
      when :thumb        then {:size => '75x75'}
      when :mobile_thumb then {:size => '40x40'}
      else {}
    end
    img_options.reverse_merge! :border => 0

    image_tag product.photo.url(style), img_options
  end

  def published_products_tag_cloud(css_class_list, &block)
    tag_cloud( Product.accessible_by(current_ability)
                 .where(:products => {:approval_state => 'published'})
                 .top_tags(),
               css_class_list, &block )
  end
end

app/views/products/_form.html.haml
#product_edit
  = form_for @product, :html => { :multipart => true } do |f|

    - if @product.errors.any?
      #error_explanation
        = _("Validation errors prohibited this product from being saved")
        %ul
          = @product.errors.full_messages.each do |msg|
            %li= msg

    %p
      = _("Please fill in the following form.")
      %br
      = _("Fields marked with asterisk (*) are compulsory")

    #product_edit_fields
      %dl
        %dt= f.label :name, _('Name of the product') + ' *:'
        %dd= f.text_field :name, :class => "textfield"

      %dl
        %dt= f.label :url,_('URL') + ' *:'
        %dd= f.text_field :url, :class => "textfield"

      %dl
        %dt= f.label :description, _('Description') + ' *:'
        %dd
          = substitute_links _('This field supports Markdown formatting ([[more information]])'),
                             page_path(:markdown_help),
                             :target => '_blank', :class => 'ajax-popup'
          %br
          = f.text_area :description, :class => "textfield"

      %dl
        %dt= f.label :platforms, _('Choose a platform') + ' *:'
        %dd
          = f.collection_select :platforms, Platform.all, :id, :name,
                                { :prompt => true,
                                  :selected => @product.platform_ids },
                                { :class => 'otherfield',
                                  :name => 'product[platform_ids][]' }

      %dl
        %dt= f.label :photo, (@product.photo? ? _('Change Photo') : _('Add Photo')) + ' :'
        %dd
          - if @product.photo?
            = _('Current photo:')
            = link_to @product.photo.original_filename, @product.photo.url
            (#{number_to_human_size(@product.photo.size)})
            = surround '(', ')' do
              = capture_map_join_nowrap @product.photo.styles do |stylename, _|
                = link_to stylename, @product.photo.url(stylename)
            %span#product_edit_delete_photo
              = f.check_box(:delete_photo) + f.label(:delete_photo, _('Delete'), :class=>'checkbox-label')
            %br
            = f.label :photo, _('Replace with:')
          = f.file_field :photo, :class => 'otherfield'

      %dl
        %dt= f.label :tag_list, _('Tags') + ' :'
        %dd= f.text_field :tag_list, :class => "textfield",
                          'data-autocomplete-url' => url_for(:action => :autocomplete_tags, :format => :json)

      %dl#product_edit_downloads
        %dt= _('Downloads') + ' :'
        %dd
          %ul#product_edit_download_list
            = render :partial => "downloads/formfields",
                     :collection => @product.downloads.find_all(&:valid?),
                     :as => :download,
                     :locals => { :edit => true, :delete => true, :form => f }
          %dl#product_new_download
            %dt= _('Add a new download:')
            %dd.product-download-formfields
              = f.fields_for :downloads, @product.downloads.build do |d|
                .product-download-formfields-line
                  = d.label :title, _('Title') + ':'
                  = d.text_field :title, :class => "textfield"
                .product-download-formfields-line
                  = d.label :file, _('File') + ':'
                  = d.file_field :file, :class => 'otherfield'
                -# make weight field hidden if the product has no downloads
                - if @product.downloads.find_all(&:valid?).empty?
                  = d.hidden_field :weight, :value => 1, :class => 'product-download-order-field'
                - else
                  .product-download-formfields-line.product-download-order
                    = d.label :weight, _('Order') + ':'
                    = d.number_field :weight,
                                     :value => @product.downloads.map(&:weight).max + 1,
                                     :class => 'textfield product-download-order-field',
                                     :size => 5, :step => 'any'

      - if @product.new_record?
        %dl
          %dt= _('Terms and conditions')
          %dd
            = f.check_box :terms
            = f.label :terms,
                substitute_links( _('I accept the OtaSizzle [[Publisher Terms and Conditions]]'),
                                  page_path(:publisher_terms),
                                  :target => '_blank', :class => 'ajax-popup' ),
                :class => 'checkbox-label'

      %dl
        %dt
        %dd
          = f.submit _('Submit'), :class => 'smallbutton'
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          = f.submit _('Cancel'), :name => 'cancel', :class => 'smallbutton'

app/views/products/_main_productlist.html.haml
-# Shows the main product list including the header and paginator

:ruby
  # determine which title to use
  title = case @view_type
    when :myapps
      _("Listing my applications")
    when :approval
      _("Listing applications with status: %{status}") % {:status => approval_status(@approval_state)}
    when :index then case
      when @search
        _("Search results")
      when @platform.present? && @tags.present?
        n_("Listing %{platform} applictions with the tag %{tags}",
           "Listing %{platform} applictions with tags %{tags}",
           @tags.count
          ) % {:tags => @tags.to_sentence(:two_words_connector => _(' or '), :last_word_connector => _(', or '))}
      when @tags.present?
        n_("Listing applictions with the tag %{tags}",
           "Listing applictions with tags %{tags}",
           @tags.count
          ) % {:tags => @tags.to_sentence(:two_words_connector => _(' or '), :last_word_connector => _(', or '))}
      when @platform.present?
        _("Listing %{platform} applications") % {:platform => @platform.name}
      else
        _("Listing all applications")
      end
  end

- if @products.blank?
  #browse_products
    %h1= title
    #no_products_msg= _("No applications available.")

- else
  #browse_products
    %h1= title

    -# make a list of sort headers separated by "|"
    :ruby
      sort_headers = [
        ['created_at', _('Publication date')],
        ['popularity', _('Popularity')],
        ['avg_rating', _('User rating')],
      ]
    #browse_products_sort
      = capture_map_join sort_headers, ' | ' do |key, title|
        - if key == @sort
          %span.selected-sort-key= title
        - else
          = link_to title, products_path_with_params(:sort => key)
    %br
    = render :partial => 'products', :object => @products

  #browse_paginate
    = will_paginate @products,
                    :previous_label => _('&#8592; Previous'),
                    :next_label     => _('Next &#8594;')

app/views/products/_products.html.haml
- reset_cycle 'browse_products'
.product_list
  - products.each do |product|
    -# Using a block-level link, which is allowed in HTML5 but not in
    -# XHTML Basic. In practice all browsers support it, but we'll add
    -# 'style="display: block"' just to be safe.
    = link_to(product, :style => 'display: block') do
      .browse_product{:class => cycle("browse_product_left", "browse_product_right", :name=>'browse_products')}
        .browse_product_picture
          = product_photo(product, (mobile_device? ? :mobile_thumb : :thumb))

        .browse_product_info
          .browse_row.product_name= product.name
          .browse_row
            = _("Publisher:")
            = user_link product.publisher, :nolink
          .browse_row
            = _("Popularity: ")
            = product.popularity
          .browse_row
            = _("Rating") + ':'
            = render :partial =>'ratings/rating',
                     :object => product.avg_rating,
                     :locals => { :empty_message => '' }

          - if [:myapps, :approval].include?(@view_type) || (logged_in? && current_user.is_admin?)
            .browse_row
              = _("State:")
              = approval_status product

        .browse_product_desc.markdown-content
          -# :no_links is needed, because we're inside a block-level link
          -# and nested links are not allowed
          = product.description_html(:no_links, :no_image)

app/views/products/_search.haml
#search
  - if can? :index, Product
    = form_tag(products_path, :method => :get) do
      = search_field_tag 'q', nil, :maxlength=>20, :size=>10, :class=>'searchfield'
      = submit_tag _('search'), :class => 'bigbutton'

app/views/products/_tag_cloud.html.haml
.tag-cloud
  - published_products_tag_cloud((1..6).map {|i| "tag-cloud-tag-size#{i}"}) do |tag, css_class|
    %span.tag-cloud-tag{:class => css_class}= tag_link tag

app/views/products/edit.html.haml
#product-edit.product-edit
  %h1= _("Editing product")
  = render 'form'
  = button_to _('Back'), :back, :class => 'smallbutton', :method => :get

app/views/products/index.html.haml
- unless @err_msg.blank?
  %br
  %br
  #browse_search_err_msg(align="center")
    %h1= @err_msg

= render :partial => 'main_productlist'

app/views/products/mainpage.html.haml
-# TODO: replace align="center" with a css rule
#welcome_msg(align="center")
  = render :partial => '/welcome_message'

#browse_tags
  %h1= _('Tags')
  = render 'tag_cloud'

- if @featured_products.present?
  #browse_featured_products
    %h1
      - if @platform.present?
        = _("Listing featured %{platform} applications") % {:platform => @platform.name}
      - else
        = _("Listing featured applications")
    = render :partial=>'products', :object => @featured_products

- if mobile_device?
  %h2= link_to _("Browse all applications"), products_path
- else
  = render :partial => 'main_productlist'

app/views/products/new.html.haml
#product-new.product-edit
  %h1= _("Add a product")
  = render 'form'
  = button_to _('Back'), products_path, :class => 'smallbutton', :method => :get

app/views/products/show.html.haml
%h1#product-title= "#{@product.name} - #{_("Detailed view")}"

#product-info
  #product-image
    #product-image-border
      #image= image_tag @product.photo.url(:small)

  #product-details
    %dl#product-publisher
      %dt= _("Publisher")
      %dd= user_link @product.publisher

    %dl#product-platform
      %dt= n_("Platform", "Platforms", @product.platforms.length)
      %dd= map_join_nowrap(@product.platforms) {|p| link_to p.name, platform_products_path(p) }

    %dl#product-published
      %dt= _("Published")
      %dd= l @product.updated_at.to_date, :format => :long

    %dl#product-popularity
      %dt= _("Number of views")
      %dd= @product.popularity

    %dl#product-rating
      %dt= _("Rating")
      %dd
        = render :partial => 'ratings/rating', :object => @product.avg_rating
        - if logged_in? && @product.publisher != current_user
          #product-rating-form= render 'ratings/form'

    %dl#product-url
      %dt= _("URL")
      %dd= link_to @product.url, "http://"+@product.url, :target => '_blank'

    %dl#product-tags
      %dt= _("Tags")
      %dd= map_join_nowrap(@product.tags) {|tag| tag_link tag }

    - if @product.downloads.present? && can?(:index, Download)
      %dl#product-downloads
        %dt= _("Downloads")
        %dd
          = render :partial => "downloads/list",
                   :collection => @product.downloads, :as => :download,
                   :locals => { :delete => true, :form => nil }

    %dl#product-description
      %dt= _("Description")
      %dd.markdown-content= @product.description_html

    - if @product.featured
      %dl#product-featured
        %dt= _("Featured")
        %dd= mobile_device? ? s_('is_featured|yes') : '✓'

    - if @product.approval_state == 'published' || @approval_buttons.present?
      %dl#product-approval-state
        %dt= s_("approval_status|Status")
        %dd
          = approval_status(@product)
          - if @approval_buttons.include? :request_approval
            %dd
              = button_to _("Request approval"), request_approval_product_path(@product), :method => :put,
                          :class => 'smallbutton'
          - if @approval_buttons.include? :approve
            %dd
              = button_to _("Approve"), approve_product_path(@product), :method => :put,
                          :class=>"smallbutton",
                          :confirm => _('Are you sure you want to approve this product?')
          - if @approval_buttons.include? :block
            %dd
              = button_to _("Block"), block_product_path(@product), :method => :put,
                          :class => 'smallbutton',
                          :confirm => _('Are you sure you want to block this product?')

    :ruby
      buttons =
        [:edit, :delete, :promote, :demote].
          keep_if { |action| can? action, @product }
    - unless buttons.empty?
      %dl#product-admin
        %dt= _("Admin")
        - if buttons.include? :edit
          %dd= button_to _('Edit'), edit_product_path(@product), :method => :get, :class => "smallbutton"
        - if buttons.include? :delete
          %dd
            = button_to _('Delete'), @product, :method => :delete,
                        :class=>"smallbutton",
                        :confirm => _('Are you sure?')
        - if buttons.include?(:promote) && !@product.featured
          %dd
            = button_to _("Make featured"), promote_product_path(@product), :method => :put,
                        :class => 'smallbutton'
        - if buttons.include?(:demote) && @product.featured
          %dd
            = button_to _("Remove from featured"), demote_product_path(@product), :method => :put,
                        :class => 'smallbutton'

    %br
    = button_to _('Report issue'), 'http://www.sizzlelab.org/contact', :method => :get,
                :class => 'smallbutton'

#product-comments
  - if can? :show, Comment
    - if !@admin_comments.empty? || @new_admin_comment
      %h2= _("Admin comments")
      :ruby
        msg = _("These comments are only shown to administrators and %{comments_shown_for}.") % {
          :comments_shown_for =>
            if @product.publisher == current_user
              s_("comments_shown_for|you")
            else
              s_("comments_shown_for|the publisher of the product")
            end
        }
      %p= msg

      #product-admin-comment-list
        = render :partial => "comment/list", :collection => @comments, :as => :comment

  %p
    - if can? :new, Comment
      = render :partial => "comment/form"
    - else
      = _("Please login to add comments")

  = button_to _('Back'), :back, :class => 'smallbutton', :method => :get