config/routes.rb
AaltoApps::Application.routes.draw do
  # prefix all urls with language (e.g. /en/rest_of_url)
  filter :locale

  get 'session' => 'sessions#index' # login page
  post 'session' => 'sessions#create'
  get 'session/cas' => 'sessions#create', :cas => true, :as => :cas_session
  delete 'session' => 'sessions#destroy'

  resources :users do
    resources :products
    resources :comments
    resources :ratings
  end
  
  resources :platforms do
    resources :products
  end
  
  resources :products do
    resources :platforms
    resources :comments
    resources :downloads
    resources :ratings

    member do
      put :block
      put :approve
      put :request_approval
      put :promote
      put :demote
    end

    collection do
      namespace 'platform' do
        get ':platform' => 'products#index'
      end

      get 'tag/:tags' => 'products#index', :as => :tag

      get :autocomplete_tags
    end
  end

  resources :comments, :belongs_to => :products

  resources :pages, :only => :show

  # Receives proxy-granting ticket from CAS server.
  # This must be called using HTTPS or from localhost for security reasons.
  get 'receive_pgt' => 'cas_proxy_callback#receive_pgt'
  # used internally for retrieving PGTs
  get 'retrieve_pgt' => 'cas_proxy_callback#retrieve_pgt'

  root :to => "products#mainpage"

  # if no other routes match, render error page
  match '*path' => ApplicationController.action(:render_404)
end

app/views/layouts/_footer.html.haml
.footer_text
  %a(target="_blank" href="http://www.sizzlelab.org") Sizzlelab.org
  \|
  %a(target="_blank" href="http://otasizzle.wordpress.com") OtaSizzle blog
  \|
  %a(target="_blank" href="http://www.sizzlelab.org/content/legal-information") Legal Information
  \|
  %a(target="_blank" href="http://www.sizzlelab.org/content/frequently-asked-questions-faq") FAQ
  \|
  %a(target="_blank" href="http://www.sizzlelab.org/content/howto") HOWTOs
  \|
  %a(target="_blank" href="http://www.sizzlelab.org/contact") Feedback

app/views/layouts/_locale_selector.html.erb
<span class="locale_selector"><%=
  raw @available_locales.map { |l|
    if l[:current?]
      content_tag(:span, l[:name], :class => 'current_locale')
    else
      link_to l[:name], params.merge(:locale => l[:id])
    end
  }.join(', ')
%></span>

app/views/layouts/_menu.html.haml
:ruby
  # determine which menus to show
  abilities = can?(:approve, Product), can?(:index, User), can?(:index, Platform)
  can_approve, can_index_users, can_index_platforms = abilities
  show_admin_menu = abilities.any?

#menu
  .navmenu
    #menu-home
      = link_to _("home"), root_path, :class => 'menusingle'
    #menu-browse
      .menutop= _("browse")
      %ul
        %li.submenu_row= link_to _("All"), products_path
        - Platform.all.each do |platform|
          %li.submenu_row
            = link_to platform.name, platform_products_path(platform)
    - if logged_in?
      #menu-publish
        .menutop= _("publish")
        %ul
          %li.submenu_row= link_to _("My Apps"), products_path(:myapps=>true)
          %li.submenu_row= link_to _("New App"), new_product_path
    - if show_admin_menu
      #menu-admin
        .menutop= _("admin")
        %ul
          - if can_approve
            %li.submenu_row
              = link_to _('Products pending approval'), products_path(:approval => 'pending')
            %li.submenu_row
              = link_to _('Blocked products'), products_path(:approval => 'blocked')
          - if can_index_users
            %li.submenu_row= link_to _('Users'), users_path
          - if can_index_platforms
            %li.submenu_row= link_to _('Platforms'), platforms_path

app/views/layouts/_mobile_version_selector.html.haml
%span.mobile_version_selector
  - if mobile_device?
    = link_to _("Switch to standard version"), :mobile => '0'
  - else
    = link_to _("Switch to mobile version"), :mobile => '1'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= _("Aalto Apps")

    -# pass translated strings to javascript
    -# (passing plural forms won't work with this simple method)
    :javascript
      var translations = {
        edit:    '#{escape_javascript raw _('Edit')}',
        cancel:  '#{escape_javascript raw _('Cancel')}',
        loading: '#{escape_javascript raw _('loading...')}',
        close:   '#{escape_javascript raw _('Close')}',
        accept:  '#{escape_javascript raw _('Accept')}',
        decline: '#{escape_javascript raw _('Decline')}',
        new_download: '#{escape_javascript raw _('Add new download')}',
        remove_download: '#{escape_javascript raw _('Cancel adding this download')}',
        move_up:   '#{escape_javascript raw _('Move up')}',
        move_down: '#{escape_javascript raw _('Move down')}'
      };

    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body{:lang => I18n.locale}
    .layout_whole
      .wrapper_top
        .layout_logo
          = link_to root_path do
            aalto apps

        .layout_info
          .layout_menuitem
            = _("Choose language:")
            = render :partial => '/layouts/locale_selector'
          .layout_menuitem= render :partial => '/layouts/mobile_version_selector'
          .layout_menuitem= render :partial => '/users/login_menu'
          .layout_menuitem= render :partial => '/products/search'

      .layout_frame
        .layout_master
          - if notice
            #notice= notice
          - if alert
            #alert= alert
          = content_for?(:content) ? yield(:content) : yield

        = render :partial => '/layouts/footer'
        .clear

    = render :partial => '/layouts/menu'

app/views/layouts/error.html.haml
= content_for :content do
  .error-message= yield

= render :file => "layouts/#{mobile_device? ? 'mobile_application' : 'application'}"

app/views/layouts/mobile_application.html.haml
!!! XML
!!! Basic
%html(xmlns="http://www.w3.org/1999/xhtml")
  %head
    %title= _("Aalto Apps")

    -# viewport scaling settings for mobile browsers:
    -# - no unnecessary horizontal scrolling
    -# - sane initial zoom level
    -# - allow zooming out
    -#<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=0.5" />
    %meta(name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=0.5")

    -# use IE7.js (http://code.google.com/p/ie7-js/) to fix some HTML/CSS
    -# issues in older IEs
    <!--[if lt IE 9]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
    <![endif]-->

    = stylesheet_link_tag 'mobile_application'
    = javascript_include_tag 'mobile_application'
    = csrf_meta_tags

  %body{:lang => I18n.locale}
    .layout_whole
      .wrapper_top
        .layout_logo
          = link_to root_path do
            aalto apps

        .layout_info
          #top_menu.layout_menuitem
            = link_to _("home"), root_path
            = link_to _("browse"), '#menu-browse'
            = link_to _("main menu"), '#menu'
            = link_to _("search"), '#search'
          .layout_menuitem
            = _("Choose language:")
            = render :partial => '/layouts/locale_selector'
          .layout_menuitem= render :partial => '/layouts/mobile_version_selector'
          .layout_menuitem= render :partial => "/users/login_menu"

      .layout_frame
        .layout_master
          - if notice
            #notice= notice
          - if alert
            #alert= alert
          = content_for?(:content) ? yield(:content) : yield

        = render :partial => '/layouts/menu'
        = render :partial => "/products/search"

        = render :partial => '/layouts/footer'